# SEARCH_TOPICS was pulled from Ranker.com pending a better source
# https://www.ranker.com/list/social-issues-in-america-that-you-care-about-most/mike-rothschild
SEARCH_TOPICS = ["homeless",
                 "lgbt",
                 "education",
                 "ineffective government",
                 "poverty",
                 "pollution",
                 "civil rights",
                 "affordable housing",
                 "immigration",
                 "police brutality",
                 "health care",
                 "corporate influence",
                 "student loan debt",
                 "climate change",
                 "racism",
                 "unemployment",
                 "terrorism",
                 "green energy",
                 "income inequality",
                 "abortion",
                 "bullying",
                 "animal rights",
                 "vaccines",
                 "campaign finance reform",
                 "gun control"]

SEARCH_TOPICS_SIMILAR_TERMS = {
    'homeless':
        ['homelessness',
         'homeless',
         'housing',
         'shelter'],
    'lgbt':
        ['lgbt',
         'queer',
         'lesbian',
         'gay',
         'bisexual',
         'transgender'],
    'ineffective government':
        ['failure',
         'ineffective',
         'government',
         'demand',
         'improvement',
         'outcome'],
    'poverty':
        ['world',
         'poverty',
         'basic',
         'money',
         'countries',
         'children',
         'income',
         'services',
         'access'],
    'pollution':
        ['system',
         'nuclear',
         'consequences',
         'industrial'],
    'education':
        ['education',
         'learning',
         'psychology',
         'educational',
         'university',
         'school'],
    'civil rights':
        ['rights',
         'civil',
         'liberty',
         'laws',
         'right',
         'declaration'],
    'affordable housing':
        ['housing',
         'affordable',
         'cost',
         'balanced',
         'distribution',
         'affordability'],
    'immigration':
        ['immigrants',
         'immigration',
         'economic',
         'emigration'],
    'police brutality':
        ['police',
         'brutality',
         'officers',
         'officer',
         'violence'],
    'health care':
        ['health',
         'care',
         'services'],
    'corporate influence':
        ['corporate',
         'influence',
         'legislation',
         'regulators',
         'economic',
         'bailouts',
         'interests'],
    'student loan debt':
        ['loan',
         'student',
         'debt',
         'loans',
         'borrowers',
         'borrower'],
    'climate change':
        ['climate',
         'change',
         'warming',
         'global',
         'greenhouse',
         'emissions'],
    'racism':
        ['race',
         'racist',
         'racial',
         'discrimination'],
    'unemployment':
        ['unemployed',
         'workers',
         'wages',
         'employment',
         'increased',
         'work',
         'labour',
         'jobs'],
    'terrorism':
        ['terrorist',
         'terrorists',
         'terrorism'],
    'green energy':
        ['energy',
         'sustainable',
         'environmental',
         'nuclear',
         'grid'],
    'income inequality':
        ['inequality',
         'income'],
    'abortion':
        ['fetus',
         'abortions',
         'trimester',
         'pro-choice'],
    'bullying':
        ['bully'],
    'animal rights':
        ['animal',
         'animals',
         'animal rights'],
    'vaccines':
        ['herpesvirus',
         'smallpox',
         'vaccines'],
    'campaign finance reform':
        ['campaign',
         'reform',
         'finance',
         'campaign finance reform'],
    'gun control':
        ['control',
         'gun',
         'gun control',
         'firearms',
         'homicides']}
